---
- name: "Check if dir exists {{ dotfiles_home }}{{ dotfiles_dest }}"
  stat:
    path: "{{ dotfiles_home }}{{ dotfiles_dest }}"
  register: check_dir

- name: "Clone repository {{ dotfiles_repo }} to {{ dotfiles_home }}{{ dotfiles_dest }}"
  expect:
    command: "git clone {{ dotfiles_repo }} {{ dotfiles_home }}{{ dotfiles_dest }}"
    responses:
      Username: "{{ dotfiles_username }}"
      Password: "{{ dotfiles_password }}"
  no_log: false
  when: (check_dir.stat.exists == false)
