---
- name: Converge
  hosts: all

  vars_files:
    - secrets.yml
    - vars.yml

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      become: yes
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Install prerequisites
      block:
      - name: Install pexpect
        pip:
          name: pexpect

      - name: Install git
        import_role:
          name: geerlingguy.git
      become: yes

    - name: Install dotfiles
      include_role:
        name: mrxcitement.dotfiles
      vars:
        dotfiles_repo: '{{ item.repo }}'
        dotfiles_dest: "{{ item.dest }}"
        dotfiles_version: '{{ item.version }}'
        dotfiles_username: '{{ item.username | default("") }}'
        dotfiles_password: '{{ item.password | default("") }}'
      loop: '{{ dotfiles }}'
